server:
  port: 8081
  servlet:
    context-path: /you
    
    
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: scott
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver 
     